namespace EphemerisIII

module License =
    let LICENSE_TEXT =
        "EphemerisII - A Gloranthan Planetarium\r\n"
        + "Version 1.4 for Java 1.6+ Coded & copyright Mr. Tines <tines@windsong.demon.co.uk> 1998-2010\r\n"
        + "Version 1.0 for OpenSilver2.1+ Coded & copyright Steve Gilham <SteveGilham@users.noreply.github.com> 2024\r\n\r\n"
        + "This program is a separate implementation of the ideas of Greg Stafford "
        + "based upon the original Gloranthan ephemeris program by Nick Brooke "
        + "<Nick_Brooke@compuserve.com>, whose star position data and holy day collation "
        + "were invaluable.\r\n"
        + "A number of transient (Sky Storm), unpredictable (Jugger), minor (One night "
        + "wish), variable (Arkat) or just plain ill defined (Ice Palace) features are "
        + "not even attempted in this model.\r\n\r\n"
        + "All rights reserved.  Full licence details follow:-\r\n\r\n"
        + "Standard License for Gloranthan fan material (NOT YET GRANTED : limited release for review only) -\r\n\r\n"
        + "\"Glorantha is a trademark of Chaosium, Inc.  Gloranthan material is copyright "
        + "1997 by Mr. Tines, Nick Brooke, and Greg Stafford.  Glorantha is the creation "
        + "of Greg Stafford, and is used with his permission.\"\r\n\r\n"
        + "The above applies to the the work considered as a whole and any source files "
        + "not separately enumerated below.\r\n\r\n"
        + "All these software components in composition listed here\r\n\r\n"
        + "[None so far]\r\n\r\n"
        + "are covered by the\r\n"
        + "What the Fuck Public Licence.\r\n\r\n"
        + "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\r\n"
        + "Version 2, December 2004\r\n\r\n"
        + "Copyright (C) 2004 Sam Hocevar\r\n"
        + "14 rue de Plaisance, 75014 Paris, France\r\n"
        + "Everyone is permitted to copy and distribute verbatim or modified "
        + "copies of this license document, and changing it is allowed as long "
        + "as the name is changed.\r\n\r\n"
        + "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\r\n"
        + "TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\r\n\r\n"
        + "0. You just DO WHAT THE FUCK YOU WANT TO.\r\n"
        + "NO WARRANTY\r\n"
        + "\r\n"
        + "BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR "
        + "THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN "
        + "OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES "
        + "PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED "
        + "OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF "
        + "MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO "
        + "THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM "
        + "PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR "
        + "CORRECTION.\r\n"
        + "\r\n"
        + "IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING "
        + "WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR "
        + "REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, "
        + "INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING "
        + "OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO "
        + "LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR "
        + "THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER "
        + "PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE "
        + "POSSIBILITY OF SUCH DAMAGES.\r\n"
